// Placeholder for custom food API integration
//src/utils/foodApi.ts
import { Food } from "@/models/models";

const MOCK_FOODS: Food[] = [
  {
    id: "1",
    name: "Kanin puti (protein-reduced)",
    servingSize: "1/3 cup (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "White Rice (protein-reduced)",
  },
  {
    id: "2",
    name: "Ampaw (Pinipig)",
    servingSize: "2 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Ampaw (Pinipig)",
  },
  {
    id: "3",
    name: "Biko",
    servingSize: "1 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake (glutinous) biko",
  },
  {
    id: "4",
    name: "Cuchinta",
    servingSize: "2 pcs (60g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake, cuchinta",
  },
  {
    id: "5",
    name: "Sapin-sapin",
    servingSize: "1 slice (75g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous) sapin-sapin",
  },
  {
    id: "6",
    name: "Cornstarch",
    servingSize: "1/4 cup (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cornstarch",
  },
  {
    id: "7",
    name: "Maja Blanca",
    servingSize: "1/2 slice (65g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn pudding, maja blanca",
  },
  {
    id: "8",
    name: "Maja mais",
    servingSize: "1 slice (75g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn pudding, maja mais, yellow",
  },
  {
    id: "9",
    name: "Bihon",
    servingSize: "1 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice noodles, bihon",
  },
  {
    id: "10",
    name: "Misua",
    servingSize: "1 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Wheat noodles, thin",
  },
  {
    id: "11",
    name: "Sotanghon",
    servingSize: "1 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Noodles, mungbean, starch",
  },
  {
    id: "12",
    name: "Sweet potato noodles",
    servingSize: "1 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Noodles, sweet potato",
  },
  {
    id: "13",
    name: "Gabi",
    servingSize: "3/4 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Taro",
  },
  {
    id: "14",
    name: "Kamote (dilaw, murado, puti)",
    servingSize: "3/4 cup (85g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Sweet potato (yellow, purple, white)",
  },
  {
    id: "15",
    name: "Kamoteng kahoy / balinghoy",
    servingSize: "3/4 cup (85g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cassava",
  },
  {
    id: "16",
    name: "Kamoteng kahoy / bibingka",
    servingSize: "1 slice (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cassava cake, bibingka",
  },
  {
    id: "17",
    name: "Kamoteng kahoy / linupak",
    servingSize: "1 pc (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cassava, mashed, w/sugar and margarine",
  },
  {
    id: "18",
    name: "Kamoteng kahoy / pichi-pichi",
    servingSize: "1 pc (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cassava, pichi-pichi",
  },
  {
    id: "19",
    name: "Kamoteng kahoy / suman",
    servingSize: "1 pc (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cassava, suman",
  },
  {
    id: "20",
    name: "Tugi",
    servingSize: "1 1/4 cup (150g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Yam, spiny",
  },
  {
    id: "21",
    name: "Ubi (purple yam)",
    servingSize: "1 1/4 cup (130g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Yam, purple",
  },
  {
    id: "22",
    name: "Saging saba, nilaga",
    servingSize: "1 pc (65g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Saba banana, boiled",
  },
  {
    id: "23",
    name: "Sago nilaga",
    servingSize: "1/2 cup (120g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Palm starch ball, boiled",
  },
  {
    id: "24",
    name: "Sago tapioca",
    servingSize: "3/4 cup (160g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 92 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 0 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Tapioca pearls",
  },
  {
    id: "25",
    name: "Bigas, puti, sinaing",
    servingSize: "1/2 cup (80g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "White Rice, well-milled, boiled",
  },
  {
    id: "26",
    name: "Bigas, puti, sinaing",
    servingSize: "1/2 cup (80g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Red Rice, undermilled, boiled",
  },
  {
    id: "27",
    name: "Pinawa Rice (brown rice)",
    servingSize: "1/2 cup (80g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice (undermilled/brown rice), boiled",
  },
  {
    id: "28",
    name: "Lugao (Thin consistency)",
    servingSize: "4 1/2 cup (705g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice porridge (thin consistency)",
  },
  {
    id: "29",
    name: "Lugao (Medium consistency)",
    servingSize: "3 cup (435g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice porridge (medium consistency)",
  },
  {
    id: "30",
    name: "Lugao (Thick consistency)",
    servingSize: "1 1/2 cup (250g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice porridge (thick consistency)",
  },
  {
    id: "31",
    name: "Ampaw rice",
    servingSize: "2 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Ampaw rice",
  },
  {
    id: "32",
    name: "Bibingka, galapong",
    servingSize: "1/2 slice (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake, bibingka",
  },
  {
    id: "33",
    name: "Bibingka, malagkit",
    servingSize: "1/2 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake (glutinous), bibingka",
  },
  {
    id: "34",
    name: "Bibingka, pinipig",
    servingSize: "1 slice (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake (glutinous), pinipig",
  },
  {
    id: "35",
    name: "Espasol",
    servingSize: "1 slice (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep, espasol",
  },
  {
    id: "36",
    name: "Kalamay, may latik",
    servingSize: "1 slice (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous), kalamay, with coconut curd topping",
  },
  {
    id: "37",
    name: "Kalamay, ube",
    servingSize: "1 slice (60g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous), with yam",
  },
  {
    id: "38",
    name: "Palitaw, walang niyog",
    servingSize: "3 pcs (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous), palitaw",
  },
  {
    id: "39",
    name: "Puto, brown",
    servingSize: "1/2 slice (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake, brown",
  },
  {
    id: "40",
    name: "Puto bumbong",
    servingSize: "2 pcs (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake, puto bumbong, purple",
  },
  {
    id: "41",
    name: "Puto maya",
    servingSize: "1/2 slice (60g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake, maya",
  },
  {
    id: "42",
    name: "Puto, puti",
    servingSize: "3 pcs (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake, puto white",
  },
  {
    id: "43",
    name: "Puto seko",
    servingSize: "4 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice-bread prep, toasted, puto seko",
  },
  {
    id: "44",
    name: "Puto seko, may niyog",
    servingSize: "7 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice-bread prep, toasted, puto seko with grated coconut",
  },
  {
    id: "45",
    name: "Suman marwekos, may niyog",
    servingSize: "1pc (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous), with grated coconut topping",
  },
  {
    id: "46",
    name: "Suman sa ibos",
    servingSize: "1 pc (60g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous), ibos",
  },
  {
    id: "47",
    name: "Suman sa lihiya",
    servingSize: "1/2 pc (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice prep (glutinous), lye-treated",
  },
  {
    id: "48",
    name: "Tamales",
    servingSize: "2 pcs (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice flour prep, tamales",
  },
  {
    id: "49",
    name: "Tikoy",
    servingSize: "1 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake (glutinous), chinese tikoy",
  },
  {
    id: "50",
    name: "Tupig",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Rice cake (glutinous), tupig",
  },
  {
    id: "51",
    name: "Apas",
    servingSize: "7 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cookies, apas",
  },
  {
    id: "52",
    name: "Brohas",
    servingSize: "5 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cookies, lady fingers",
  },
  {
    id: "53",
    name: "Cake, mamon, tostado",
    servingSize: "3 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cake, mamon, toasted",
  },
  {
    id: "54",
    name: "Cuapao",
    servingSize: "1/2 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Steamed bun",
  },
  {
    id: "55",
    name: "Hopyang hapon",
    servingSize: "1 pc (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Japanese bread, hopiang hapon",
  },
  {
    id: "56",
    name: "Marie",
    servingSize: "8 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cookies, marie",
  },
  {
    id: "57",
    name: "Pasencia",
    servingSize: "7 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cookies, pasencia",
  },
  {
    id: "58",
    name: "Pianono",
    servingSize: "1 slice (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Cake, jelly roll",
  },
  {
    id: "59",
    name: "Sponge Cake",
    servingSize: "1 slice (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Sponge cake",
  },
  {
    id: "60",
    name: "Binatog",
    servingSize: "1/2 cup (90g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Hominy",
  },
  {
    id: "60",
    name: "Corn flakes",
    servingSize: "1/2 cup (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn flakes",
  },
  {
    id: "61",
    name: "Mais butil, de lata",
    servingSize: "1 cup (160g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn whole kernels, canned",
  },
  {
    id: "62",
    name: "Main cream style, de lata",
    servingSize: "1/2 cup (130g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn cream style, canned",
  },
  {
    id: "63",
    name: "Mais durog",
    servingSize: "1 cup (120g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn grits (yellow, white)",
  },
  {
    id: "64",
    name: "Mais sa busal",
    servingSize: "1/2 pc (65g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Corn on the cob (yellow, white)",
  },
  {
    id: "65",
    name: "Patatas",
    servingSize: "1pc (170g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Potato",
  },
  {
    id: "66",
    name: "Kastanyas",
    servingSize: "8 pcs (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Chestnuts, roasted",
  },
  {
    id: "67",
    name: "Plantains, saba",
    servingSize: "1 pc (80g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 100 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 2 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Plantains",
  },
  {
    id: "68",
    name: "Bread, wheat",
    servingSize: "1 1/2 pcs (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, wheat",
  },
  {
    id: "69",
    name: "Ensaymada",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, sweet roll",
  },
  {
    id: "70",
    name: "Hamburger bun",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, hamburger bun",
  },
  {
    id: "71",
    name: "Hotdog roll",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, hotdog roll",
  },
  {
    id: "72",
    name: "Loaf bread, Pan Amerikano",
    servingSize: "2 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, white, loaf",
  },
  {
    id: "73",
    name: "Pan de bonete",
    servingSize: "1 1/2 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pan de bonete",
  },
  {
    id: "74",
    name: "Pan de leche",
    servingSize: "1/2 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pan de leche",
  },
  {
    id: "75",
    name: "Pan de limon",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pan de limon",
  },
  {
    id: "76",
    name: "Pan de monay",
    servingSize: "1/2 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pan de monay",
  },
  {
    id: "77",
    name: "Pan de sal",
    servingSize: "1 1/2 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pan de sal",
  },
  {
    id: "78",
    name: "Pinagong",
    servingSize: "1/2 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pinagong",
  },
  {
    id: "79",
    name: "Pita bread, white",
    servingSize: "1/2 pc (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pita, white (enriched/unenriched)",
  },
  {
    id: "80",
    name: "Pita bread, whole wheat",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, pita, whole wheat",
  },
  {
    id: "81",
    name: "Tinapay, tostado",
    servingSize: "5 pcs (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Bread, toast, toasted",
  },
  {
    id: "82",
    name: "Couscous",
    servingSize: "1 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Couscous",
  },
  {
    id: "83",
    name: "Pasta (enriched/unriched)",
    servingSize: "1/2 cup (70g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Pasta (enriched/unriched)",
  },
  {
    id: "84",
    name: "Udon",
    servingSize: "1 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Udon",
  },
  {
    id: "85",
    name: "Balat ng lumpia",
    servingSize: "7 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Spring roll wrapper, plain",
  },
  {
    id: "86",
    name: "Langka, buto",
    servingSize: "14 pcs (75g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Jackfruit, seed",
  },
  {
    id: "87",
    name: "Quinoa",
    servingSize: "1 cup (95g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 108 },
      { name: "Carbohydrate", unit: "g", amount: 23 },
      { name: "Protein", unit: "g", amount: 4 },
      { name: "Fat", unit: "g", amount: 0 },
    ],
    englishName: "Quinoa",
  },
  {
    id: "88",
    name: "Kenchi",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Beef Shank",
  },
  {
    id: "89",
    name: "Laman",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Beef Lean Meat",
  },
  {
    id: "90",
    name: "Pierna corta at pierna larga",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Beef Round",
  },
  {
    id: "91",
    name: "Solomilyo",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Beef Tenderlion",
  },
  {
    id: "92",
    name: "Tagiliran, gitna",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Beef Porterhouse steak",
  },
  {
    id: "93",
    name: "Tagiliran, hulihan",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Beef Sirlion",
  },
  {
    id: "94",
    name: "Hita",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef Round",
  },
  {
    id: "95",
    name: "Kenchi",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef Shank",
  },
  {
    id: "96",
    name: "Laman, bahagyang taba",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef, Lean meat with little fat",
  },
  {
    id: "97",
    name: "Laman, katamtamang taba",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef, lean meat with medium fat",
  },
  {
    id: "98",
    name: "Paypay",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef Chuck",
  },
  {
    id: "99",
    name: "Pierna corta at pierna larga",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef Round steak",
  },
  {
    id: "100",
    name: "Tapadera",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Carabeef Rump",
  },
  {
    id: "101",
    name: "Lomo",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Pork Tenderloin",
  },
  {
    id: "102",
    name: "Balikat",
    servingSize: "1 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Shoulder",
  },
  {
    id: "103",
    name: "Binti",
    servingSize: "1 slice,(40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Leg",
  },
  {
    id: "104",
    name: "Biyas",
    servingSize: "1 slice, (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Shank",
  },
  {
    id: "105",
    name: "Dibdib",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Breast",
  },
  {
    id: "106",
    name: "Leeg",
    servingSize: "1 slice, matchbox size (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Neck",
  },
  {
    id: "107",
    name: "Likod",
    servingSize: "1 slice, matchbox size (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Back",
  },
  {
    id: "108",
    name: "Lomo",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Loin",
  },
  {
    id: "109",
    name: "Tadyang",
    servingSize: "1 slice, (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goat Rib",
  },
  {
    id: "110",
    name: "Laman",
    servingSize: "1 slice, (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Chicken White meat",
  },
  {
    id: "111",
    name: "Pitso",
    servingSize: "1 slice, (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Chicken Breast",
  },
  {
    id: "112",
    name: "Pakpak",
    servingSize: "1 pc (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Chicken Wing",
  },
  {
    id: "113",
    name: "Palaka, laman",
    servingSize: "1 pc, big or 2pcs, small (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Frog, meat",
  },
  {
    id: "114",
    name: "Atay",
    servingSize: "1/4 cup or 1pc (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Liver (pork, beef, carabeef, chicken)",
  },
  {
    id: "115",
    name: "Baga",
    servingSize: "1/4 cup (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Lungs (pork, beef, carabeef)",
  },
  {
    id: "116",
    name: "Balun-balunan",
    servingSize: "1/4 cup or 4pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Gizzard (chicken, duck)",
  },
  {
    id: "117",
    name: "Bato",
    servingSize: "1/2 cup(45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Kidney (pork, beef, carabeef)",
  },
  {
    id: "118",
    name: "Bitukang maliit",
    servingSize: "1/4 cup (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Small intestine, barbeque",
  },
  {
    id: "119",
    name: "Bituka, manok, barbeque",
    servingSize: "2 sticks (20g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Chicken intestine, barbeque",
  },
  {
    id: "120",
    name: "Dugo",
    servingSize: "1/4 cup (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Blood (pork, beef, chicken)",
  },
  {
    id: "121",
    name: "Lapay",
    servingSize: "1/2 cup (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Spleen (pork, beef, carabeef)",
  },
  {
    id: "122",
    name: "Librilyo",
    servingSize: "1/2 cup (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Omasum (beef, carabeef)",
  },
  {
    id: "123",
    name: "Litid",
    servingSize: "1 slice matchbox size (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Tendon (beef)",
  },
  {
    id: "124",
    name: "Puso",
    servingSize: "1/4 cup (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Heart (pork, beef, carabeef)",
  },
  {
    id: "125",
    name: "Alumahan",
    servingSize: "1/2 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Mackerel, striped",
  },
  {
    id: "126",
    name: "Balokong moro",
    servingSize: "1/2 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Porgy, fresh water",
  },
  {
    id: "127",
    name: "Bangus",
    servingSize: "1 slice, matchbox size (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Milkfish",
  },
  {
    id: "128",
    name: "Dalag",
    servingSize: "1/2 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Mudfish/Murrel, striated",
  },
  {
    id: "129",
    name: "Dalagang bukid",
    servingSize: "1/2 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Caesio/Fusilier, golden",
  },
  {
    id: "130",
    name: "Dilis, buo",
    servingSize: "1/3 cup (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Anchovy, long-jawed whole",
  },
  {
    id: "131",
    name: "Dilis, walang ulo",
    servingSize: "1/4 cup (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Anchovy, long-jawed w/o head",
  },
  {
    id: "132",
    name: "Dulong",
    servingSize: "50g",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Anchovy fry",
  },
  {
    id: "133",
    name: "Galunggong",
    servingSize: "1pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Scad, round",
  },
  {
    id: "134",
    name: "Hasa-hasa",
    servingSize: "1pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Mackerel, short-bodied",
  },
  {
    id: "135",
    name: "Hito",
    servingSize: "1 slice (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Catfish, freshwater",
  },
  {
    id: "136",
    name: "Labahita",
    servingSize: "1 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Surgeon fish, blue-lined",
  },
  {
    id: "137",
    name: "Lapu-lapu",
    servingSize: "1/2 slice (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Grouper, spotted",
  },
  {
    id: "138",
    name: "Matang baka",
    servingSize: "1pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Scad, big-eyed",
  },
  {
    id: "139",
    name: "Sapsap",
    servingSize: "2 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Slipmouth, common",
  },
  {
    id: "140",
    name: "Saramulyete",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Goatfish, yellow-striped",
  },
  {
    id: "141",
    name: "Tambakol",
    servingSize: "1/2 slice (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Tuna, yellow-fin",
  },
  {
    id: "142",
    name: "Tamban",
    servingSize: "1 1/2pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Sardine, Indian",
  },
  {
    id: "143",
    name: "Tawilis",
    servingSize: "2pcs (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Sardine, bombon",
  },
  {
    id: "144",
    name: "Tilapia",
    servingSize: "1/2 slice (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
    englishName: "Tilapia",
  },
  {
    id: "145",
    name: "Tulingan",
    englishName: "Tuna, frigate/bullet",
    servingSize: "1/2 slice of (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "146",
    name: "Alimango, alige",
    englishName: "Crab, mud/mangrove, fat",
    servingSize: "1 Tbsp (15g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "147",
    name: "Alimango, laman",
    englishName: "Crab, mud/mangrove, meat",
    servingSize: "1/3 cup or 1/2 pc of (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "148",
    name: "Alimasag, alige",
    englishName: "Crab, blue swimming, fat",
    servingSize: "2 1/2 Tbsp (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "149",
    name: "Alimasag, laman",
    englishName: "Crab, blue swimming, meat",
    servingSize: "1/3 cup or 1 pc (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "150",
    name: "Balatan",
    englishName: "Sea cucumber",
    servingSize: "6 pcs (120g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "151",
    name: "Pugita",
    englishName: "Octopus",
    servingSize: "40g",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "152",
    name: "Pusit",
    englishName: "Squid",
    servingSize: "2 pcs (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "153",
    name: "Talangka",
    englishName: "Crab, shore",
    servingSize: "6 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "154",
    name: "Hipon, alamang",
    englishName: "Shrimp, sergestid",
    servingSize: "1/3 cup (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "155",
    name: "Hipon, sugpo",
    englishName: "Shrimp, giant tiger prawn",
    servingSize: "1/2 pc of (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "156",
    name: "Hipon, suwahe",
    englishName: "Shrimp, greasy bask",
    servingSize: "4 pcs (40g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "157",
    name: "Hipon, tagunton",
    englishName: "Shrimp, freshwater (small)",
    servingSize: "40g",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "158",
    name: "Hipon, ulang",
    englishName: "Shrimp freshwater",
    servingSize: "40g",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "159",
    name: "Batotoy",
    englishName: "Mollusks, Sakhalin surf clam cockles",
    servingSize: "1/3 cup or 4 pcs (60g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "160",
    name: "Lapas/Kapinan",
    englishName: "Abalone",
    servingSize: "2-3 pcs (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "161",
    name: "Kuhol, ginto",
    englishName: "Snail golden",
    servingSize: "1/3 cup or 12 pcs (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "162",
    name: "Paros",
    englishName: "Clam, rayed shell",
    servingSize: "(60g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "163",
    name: "Tuway",
    englishName: "Mollusks, hard clam",
    servingSize:
      "2 1/2 cup (with shells) or 1/4 cup (without shells) or 22 pcs (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "164",
    name: "Cottage",
    englishName: "Cottage",
    servingSize: "1/3 cup (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "165",
    name: "Tuna flakes, in brine",
    englishName: "Tuna flakes, in brine",
    servingSize: "1/4 cup (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "166",
    name: "Alakaak",
    englishName: "Croaker, plain",
    servingSize: "8 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "167",
    name: "Alumahan",
    englishName: "Mackerel, striped",
    servingSize: "2 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "168",
    name: "Bakalaw",
    englishName: "Cod",
    servingSize: "1/3 pc of (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "169",
    name: "Bisugo",
    englishName: "Nemipterid, ribbon-finned",
    servingSize: "1 pc (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "170",
    name: "Biyang puti",
    englishName: "Goby, flat-headed",
    servingSize: "1 pc or 11 pcs small (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "171",
    name: "Lapu-lapu",
    englishName: "Grouper, spotted",
    servingSize: "1 pc (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "172",
    name: "Malasugi/Espada",
    englishName: "Swordfish",
    servingSize: "3 1/2 pcs (20g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "173",
    name: "Sapsap",
    englishName: "Slipmouth, common",
    servingSize: "7 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "174",
    name: "Tamban",
    englishName: "Sardine, Indian",
    servingSize: "2 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "175",
    name: "Tanigi/Tangigi",
    englishName: "Mackerel, Spanish",
    servingSize: "25g",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "176",
    name: "Tilapia",
    englishName: "Tilapia",
    servingSize: "1 pc (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "177",
    name: "Alamang",
    englishName: "Shrimp, sergestid",
    servingSize: "1/2 cup (15g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "178",
    name: "Ayungin",
    englishName: "Theraponid, silvery",
    servingSize: "15g",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "179",
    name: "Dilis",
    englishName: "Anchovy, long-jawed",
    servingSize: "13 pcs (15g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "180",
    name: "Hibe",
    englishName: "Shrimp, small, marine",
    servingSize: "4 Tbsp (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "181",
    name: "Pusit",
    englishName: "Squid",
    servingSize: "2 pcs (15g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "182",
    name: "Sapsap",
    englishName: "Slipmouth, common",
    servingSize: "4 pcs (20g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "183",
    name: "Tamban",
    englishName: "Sardine, Indian",
    servingSize: "2 pcs (20g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "184",
    name: "Galunggong",
    englishName: "Scad, round",
    servingSize: "1/2 pc of (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "185",
    name: "Tamban",
    englishName: "Sardine, Indian",
    servingSize: "3 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "186",
    name: "Tunsoy",
    englishName: "Sardine, fimbriated",
    servingSize: "3 pcs (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 41 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 1 },
    ],
  },
  {
    id: "187",
    name: "Paypay, laman",
    englishName: "Beef Chuck, lean",
    servingSize: "1 slice,mbs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "188",
    name: "Punta y pecho",
    englishName: "Beef Brisket",
    servingSize: "1 slice,mbs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "189",
    name: "Pata",
    englishName: "Pork Leg",
    servingSize: "1 slice,mbs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "190",
    name: "Binti",
    englishName: "Chicken Leg/drumstick",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "191",
    name: "Hita",
    englishName: "Chicken Thigh",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "192",
    name: "Pakpak",
    englishName: "Chicken Wing",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "193",
    name: "Ulo",
    englishName: "Chicken Head",
    servingSize: "2 pcs (50g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "194",
    name: "Hita",
    englishName: "Duck Thigh",
    servingSize: "1 pc (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "195",
    name: "Likod",
    englishName: "Duck Back",
    servingSize: "1 slice (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "196",
    name: "Pitso",
    englishName: "Pitso Breast",
    servingSize: "1 slice,mbs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "197",
    name: "Tiyan",
    englishName: "Goat Flank",
    servingSize: "1 slice,mbs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "198",
    name: "Bituka, maliit",
    englishName: "Small intestine, carabeef",
    servingSize: "1/4 cup (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "199",
    name: "Goto",
    englishName: "Tripe, beef",
    servingSize: "3/4 cup (85g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "200",
    name: "Utak",
    englishName: "Brain (pork, beef, carabeef)",
    servingSize: "1/4 cup (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "201",
    name: "Manok, buo",
    englishName: "Chicken, whole",
    servingSize: "1 pc meduim (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "202",
    name: "Pato, maalat",
    englishName: "Duck, whole, salted",
    servingSize: "1 pc meduim (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "203",
    name: "Pugo",
    englishName: "Quail",
    servingSize: "7 pcs small (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "204",
    name: "karpa",
    englishName: "Carp",
    servingSize: "1 pc of (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "205",
    name: "Cheddar, Pasteurized, processed",
    englishName: "Cheddar, Pasteurized, processed",
    servingSize: "1 slice (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "206",
    name: "Bangus Tinapa",
    englishName: "Smoked Milkfish",
    servingSize: "1 slice (30g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "207",
    name: "Salmon sa mantika",
    englishName: "Runner, teo-finned, in oil",
    servingSize: "3 slices (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "208",
    name: "Sardinas sa tomato sauce",
    englishName: "Sardines, in tomato sauce",
    servingSize: "2 pcs (80g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "209",
    name: "Tuna spread",
    englishName: "Tuna spread",
    servingSize: "2 Tbsp (25g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "210",
    name: "Karne norte, de lata",
    englishName: "Corned beef, cnd",
    servingSize: "1/4 cup (45g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "211",
    name: "Sausage, ham",
    englishName: "Sausage, ham",
    servingSize: "2 pcs (55g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "212",
    name: "Tofu",
    englishName: "Soy bean curd, tofu",
    servingSize: "1/2 cup (100g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "213",
    name: "Tokwa",
    englishName: "Soy bean curd, tokwa",
    servingSize: "1 pc (70g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "214",
    name: "Chick, one-day-old, fried",
    englishName: "Chick, one-day-old,fried",
    servingSize: "2 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "215",
    name: "Manok, paa, barbecue",
    englishName: "Chicken feet, barbecue",
    servingSize: "4 pcs (CAP) (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
  {
    id: "216",
    name: "Manok ulo, barbecue",
    englishName: "Chicken head, barbecue",
    servingSize: "3 pcs (35g)",
    nutrients: [
      { name: "Calories", unit: "kcal", amount: 86 },
      { name: "Carbohydrate", unit: "g", amount: 0 },
      { name: "Protein", unit: "g", amount: 8 },
      { name: "Fat", unit: "g", amount: 6 },
    ],
  },
];

export async function searchFoods(query: string): Promise<Food[]> {
  const lowerQuery = query.toLowerCase();

  // Filter the MOCK_FOODS array based on the query
  const results = MOCK_FOODS.filter((food) =>
    food.name.toLowerCase().includes(lowerQuery)
  );

  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300));

  return results;
}
